name: shutter_count
description: Find out how many pictures your camera has taken.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  provider: ^4.3.3
  file_picker: ^1.13.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  fonts:
    - family: Schyler
      fonts:
        - asset: assets/fonts/Inter/Inter-100.ttf
          weight: 100
        - asset: assets/fonts/Inter/Inter-200.ttf
          weight: 200
        - asset: assets/fonts/Inter/Inter-300.ttf
          weight: 300
        - asset: assets/fonts/Inter/Inter-400.ttf
          weight: 400
        - asset: assets/fonts/Inter/Inter-500.ttf
          weight: 500
        - asset: assets/fonts/Inter/Inter-600.ttf
          weight: 600
        - asset: assets/fonts/Inter/Inter-700.ttf
          weight: 700
        - asset: assets/fonts/Inter/Inter-800.ttf
          weight: 800
        - asset: assets/fonts/Inter/Inter-900.ttf
          weight: 900
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
